export enum Color {
    GRAY, GREEN, BLACK, WHITE, BLUE, YELLOW, LIGHT_GREEN, TURQUOISE, ROYAL_BLUE, BLUE_VIOLET,
    RED, SALMON, ORANGE, MAROON, DARK_RED, BROWN, FIREBRICK, INDIAN_RED, SADDLE_BROWN, SIENNA, CHOCOLATE, PERU,
    SLATE_GRAY, LIGHT_SLATE_GRAY, TOMATO, CORAL, LIGHT_CORAL, LIGHT_SALMON, GOLD, PALE_GOLDEN_ROD, KHAKI,
    GREEN_YELLOW, PALE_GREEN, PALE_TURQUOISE, AQUA_MARINE, POWDER_BLUE, LIGHT_BLUE, LIGHT_SKY_BLUE, THISTLE,
    ANTIQUE_WHITE, BEIGE, BISQUE, BLANCHED_ALMOND, WHEAT, CORN_SILK, LEMON_CHIFFON, LIGHT_GOLDEN_ROD_YELLOW,
    LIGHT_YELLOW, MOCASSIN, NAVAJO_WHITE, PEACH_PUFF, MISTY_ROSE, LAVENDER_BLUSH, LINEN, OLD_LACE, PAPAYA_WHIP,
    SEA_SHELL, MINT_CREAM
};