with Reactive.District.Tests;
with Reactive.Directory.Street_Directory.Tests;
with Reactive.Directory.Intersection_Directory.Tests;
with Reactive.Directory.Footway_Directory.Tests;
with Reactive.Directory.Bikeway_Directory.Tests;
with Reactive.Directory.Roadway_Directory.Tests;
with Reactive.Directory.Lane_Directory.Tests;
with Reactive.Directory.Stretch_Directory.Tests;
with Reactive.Infrastructure_Registry.Tests;
with Reactive.Traveller_Registry.Tests;
with Reactive.Traffic_Light_Registry.Tests;
with Reactive.Infrastructure.Utils.Tests;
with Reactive.Infrastructure.Street.Tests;
with Reactive.Infrastructure.Street.Utils.Tests;
with Reactive.Infrastructure.Build.Config_Reader.Tests;
with Reactive.Infrastructure.Build.Street_Builder.Tests;
with Reactive.Infrastructure.Build.Intersection_Config_Reader.Tests;
with Reactive.Infrastructure.Build.Street_Config_Reader.Tests;
with Reactive.Infrastructure.Factory.Street_Factory.Bikeway_Factory.Tests;
with Reactive.Infrastructure.Factory.Street_Factory.Footway_Factory.Tests;
with Reactive.Infrastructure.Factory.Street_Factory.Roadway_Factory.Tests;
with Reactive.Infrastructure.Factory.Street_Factory.Tests;
with Reactive.Infrastructure.Building.Parking_Manager.Garage.Tests;
with Reactive.Infrastructure.Building.Host.Facility.Tests;
with Reactive.Infrastructure.Building.Host.Utils.Tests;
with Reactive.Infrastructure.Way.Utils.Tests;
with Reactive.Infrastructure.Way.Roadway.Tests;
with Reactive.Infrastructure.Way.Roadway.Utils.Tests;
with Reactive.Infrastructure.Way.Bikeway.Tests;
with Reactive.Infrastructure.Way.Bikeway.Utils.Tests;
with Reactive.Infrastructure.Way.Footway.Tests;
with Reactive.Infrastructure.Way.Footway.Utils.Tests;
with Reactive.Infrastructure.Lane.Utils.Tests;
with Reactive.Infrastructure.Lane.Roadway_Lane.Tests;
with Reactive.Infrastructure.Lane.Footway_Lane.Tests;
with Reactive.Infrastructure.Lane.Bikeway_Lane.Tests;
with Reactive.Infrastructure.Lane.Decoration.Lane_Decorator.Tests;
with Reactive.Infrastructure.Lane.Decoration.Lane_Sign_Decorator.Tests;
with Reactive.Infrastructure.Stretch.Utils.Tests;
with Reactive.Infrastructure.Stretch.Roadway_Stretch.Tests;
with Reactive.Infrastructure.Stretch.Footway_Stretch.Tests;
with Reactive.Infrastructure.Stretch.Bikeway_Stretch.Tests;
with Reactive.Infrastructure.Stretch.Decoration.Pedestrian_Crossing.Tests;
with Reactive.Infrastructure.Stretch.Decoration.Bicycle_Crossing.Tests;
with Reactive.Infrastructure.Intersection.Utils.Tests;
with Reactive.Infrastructure.Intersection.Tests;
with Reactive.Infrastructure.Intersection.Intersection_Builder.Crossroads_Builder.Tests;
with Reactive.Infrastructure.Intersection.Intersection_Builder.T_Junction_Builder.Tests;
with Reactive.Infrastructure.Intersection.Crossing.Tests;

package body Reactive_Suite is
   Result  : aliased TS.Test_Suite;
   District_Test : aliased Reactive.District.Tests.District_Test;
   Intersection_Directory_Test : aliased Reactive.Directory.Intersection_Directory.Tests.Intersection_Directory_Test;
   Street_Directory_Test : aliased Reactive.Directory.Street_Directory.Tests.Street_Directory_Test;
   Footway_Directory_Test : aliased Reactive.Directory.Footway_Directory.Tests.Footway_Directory_Test;
   Bikeway_Directory_Test : aliased Reactive.Directory.Bikeway_Directory.Tests.Bikeway_Directory_Test;
   Roadway_Directory_Test : aliased Reactive.Directory.Roadway_Directory.Tests.Roadway_Directory_Test;
   Lane_Directory_Test : aliased Reactive.Directory.Lane_Directory.Tests.Lane_Directory_Test;
   Stretch_Directory_Test : aliased Reactive.Directory.Stretch_Directory.Tests.Stretch_Directory_Test;
   Infrastructure_Registry_Test : aliased Reactive.Infrastructure_Registry.Tests.Infrastructure_Registry_Test;
   Traffic_Light_Registry_Test : aliased Reactive.Traffic_Light_Registry.Tests.Traffic_Light_Registry_Test;
   Traveller_Registry_Test : aliased Reactive.Traveller_Registry.Tests.Traveller_Registry_Test;
   Infrastructure_Utils_Test : aliased Reactive.Infrastructure.Utils.Tests.Infrastructure_Utils_Test;
   Street_Test : aliased Reactive.Infrastructure.Street.Tests.Street_Test;
   Street_Utils_Test : aliased Reactive.Infrastructure.Street.Utils.Tests.Street_Utils_Test;
   Config_Reader_Test : aliased Reactive.Infrastructure.Build.Config_Reader.Tests.Config_Reader_Test;
   Street_Builder_Test : aliased Reactive.Infrastructure.Build.Street_Builder.Tests.Street_Builder_Test;
   Intersection_Config_Reader_Test : aliased Reactive.Infrastructure.Build.Intersection_Config_Reader.Tests.Intersection_Config_Reader_Test;
   Street_Config_Reader_Test : aliased Reactive.Infrastructure.Build.Street_Config_Reader.Tests.Street_Config_Reader_Test;
   Bikeway_Factory_Test : aliased Reactive.Infrastructure.Factory.Street_Factory.Bikeway_Factory.Tests.Bikeway_Factory_Test;
   Footway_Factory_Test : aliased Reactive.Infrastructure.Factory.Street_Factory.Footway_Factory.Tests.Footway_Factory_Test;
   Roadway_Factory_Test : aliased Reactive.Infrastructure.Factory.Street_Factory.Roadway_Factory.Tests.Roadway_Factory_Test;
   Street_Factory_Test : aliased Reactive.Infrastructure.Factory.Street_Factory.Tests.Street_Factory_Test;
   Garage_Test : aliased Reactive.Infrastructure.Building.Parking_Manager.Garage.Tests.Garage_Test;
   Facility_Test : aliased Reactive.Infrastructure.Building.Host.Facility.Tests.Facility_Test;
   Host_Utils_Test : aliased Reactive.Infrastructure.Building.Host.Utils.Tests.Host_Utils_Test;
   Way_Utils_Test : aliased Reactive.Infrastructure.Way.Utils.Tests.Way_Utils_Test;
   Roadway_Test : aliased Reactive.Infrastructure.Way.Roadway.Tests.Roadway_Test;
   Roadway_Utils_Test : aliased Reactive.Infrastructure.Way.Roadway.Utils.Tests.Roadway_Utils_Test;
   Bikeway_Test : aliased Reactive.Infrastructure.Way.Bikeway.Tests.Bikeway_Test;
   Bikeway_Utils_Test : aliased Reactive.Infrastructure.Way.Bikeway.Utils.Tests.Bikeway_Utils_Test;
   Footway_Test : aliased Reactive.Infrastructure.Way.Footway.Tests.Footway_Test;
   Footway_Utils_Test : aliased Reactive.Infrastructure.Way.Footway.Utils.Tests.Footway_Utils_Test;
   Lane_Utils_Test : aliased Reactive.Infrastructure.Lane.Utils.Tests.Lane_Utils_Test;
   Roadway_Lane_Test : aliased Reactive.Infrastructure.Lane.Roadway_Lane.Tests.Roadway_Lane_Test;
   Footway_Lane_Test : aliased Reactive.Infrastructure.Lane.Footway_Lane.Tests.Footway_Lane_Test;
   Bikeway_Lane_Test : aliased Reactive.Infrastructure.Lane.Bikeway_Lane.Tests.Bikeway_Lane_Test;
   Lane_Decorator_Test : aliased Reactive.Infrastructure.Lane.Decoration.Lane_Decorator.Tests.Lane_Decorator_Test;
   Lane_Sign_Decorator_Test : aliased Reactive.Infrastructure.Lane.Decoration.Lane_Sign_Decorator.Tests.Lane_Sign_Decorator_Test;
   Stretch_Utils_Test : aliased Reactive.Infrastructure.Stretch.Utils.Tests.Stretch_Utils_Test;
   Roadway_Stretch_Test : aliased Reactive.Infrastructure.Stretch.Roadway_Stretch.Tests.Roadway_Stretch_Test;
   Footway_Stretch_Test : aliased Reactive.Infrastructure.Stretch.Footway_Stretch.Tests.Footway_Stretch_Test;
   Bikeway_Stretch_Test : aliased Reactive.Infrastructure.Stretch.Bikeway_Stretch.Tests.Bikeway_Stretch_Test;
   Pedestrian_Crossing_Test : aliased Reactive.Infrastructure.Stretch.Decoration.Pedestrian_Crossing.Tests.Pedestrian_Crossing_Test;
   Bicycle_Crossing_Test : aliased Reactive.Infrastructure.Stretch.Decoration.Bicycle_Crossing.Tests.Bicycle_Crossing_Test;
   Intersection_Utils_Test : aliased Reactive.Infrastructure.Intersection.Utils.Tests.Intersection_Utils_Test;
   Intersection_Test : aliased Reactive.Infrastructure.Intersection.Tests.Intersection_Test;
   Crossroads_Builder_Test : aliased Reactive.Infrastructure.Intersection.Intersection_Builder.Crossroads_Builder.Tests.Crossroads_Builder_Test;
   T_Junction_Builder_Test : aliased Reactive.Infrastructure.Intersection.Intersection_Builder.T_Junction_Builder.Tests.T_Junction_Builder_Test;
   Intersection_Crossing_Test : aliased Reactive.Infrastructure.Intersection.Crossing.Tests.Intersection_Crossing_Test;

   function Suite
      return TS.Access_Test_Suite is
   begin
      TS.Add_Test (Result'Access, District_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Directory_Test'Access);
      TS.Add_Test (Result'Access, Street_Directory_Test'Access);
      TS.Add_Test (Result'Access, Footway_Directory_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Directory_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Directory_Test'Access);
      TS.Add_Test (Result'Access, Lane_Directory_Test'Access);
      TS.Add_Test (Result'Access, Stretch_Directory_Test'Access);
      TS.Add_Test (Result'Access, Infrastructure_Registry_Test'Access);
      TS.Add_Test (Result'Access, Traveller_Registry_Test'Access);
      TS.Add_Test (Result'Access, Traffic_Light_Registry_Test'Access);
      TS.Add_Test (Result'Access, Infrastructure_Utils_Test'Access);
      TS.Add_Test (Result'Access, Street_Test'Access);
      TS.Add_Test (Result'Access, Street_Utils_Test'Access);
      TS.Add_Test (Result'Access, Config_Reader_Test'Access);
      TS.Add_Test (Result'Access, Street_Builder_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Config_Reader_Test'Access);
      TS.Add_Test (Result'Access, Street_Config_Reader_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Factory_Test'Access);
      TS.Add_Test (Result'Access, Footway_Factory_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Factory_Test'Access);
      TS.Add_Test (Result'Access, Street_Factory_Test'Access);
      TS.Add_Test (Result'Access, Garage_Test'Access);
      TS.Add_Test (Result'Access, Facility_Test'Access);
      TS.Add_Test (Result'Access, Host_Utils_Test'Access);
      TS.Add_Test (Result'Access, Way_Utils_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Utils_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Utils_Test'Access);
      TS.Add_Test (Result'Access, Footway_Test'Access);
      TS.Add_Test (Result'Access, Footway_Utils_Test'Access);
      TS.Add_Test (Result'Access, Lane_Utils_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Lane_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Lane_Test'Access);
      TS.Add_Test (Result'Access, Footway_Lane_Test'Access);
      TS.Add_Test (Result'Access, Lane_Decorator_Test'Access);
      TS.Add_Test (Result'Access, Lane_Sign_Decorator_Test'Access);
      TS.Add_Test (Result'Access, Roadway_Stretch_Test'Access);
      TS.Add_Test (Result'Access, Bikeway_Stretch_Test'Access);
      TS.Add_Test (Result'Access, Footway_Stretch_Test'Access);
      TS.Add_Test (Result'Access, Pedestrian_Crossing_Test'Access);
      TS.Add_Test (Result'Access, Bicycle_Crossing_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Test'Access);
      TS.Add_Test (Result'Access, Stretch_Utils_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Utils_Test'Access);
      TS.Add_Test (Result'Access, Crossroads_Builder_Test'Access);
      TS.Add_Test (Result'Access, T_Junction_Builder_Test'Access);
      TS.Add_Test (Result'Access, Intersection_Crossing_Test'Access);
      return Result'Access;
   end Suite;
end Reactive_Suite;
