################################################################################
# Provide a "empty" image for data volume containers
################################################################################
# base image
FROM busybox:latest

# create the volume for the data
VOLUME ["/home/cds"]